[package]
name = "myslowparser"
version = "1.1.7"
authors = ["Alexander Kozharsky <a.kozharsky@icloud.com>"]

[dependencies]
regex = "1.0.4"
lazy_static = "1.1.0"
chrono = "0.4.6"
clap = "2.32.0"
rocket = "0.3.16"
rocket_codegen = "0.3.16"
